### ISSUE TITLE
Publishing Migrations

### ISSUE THREAD

**Issue by mohd-bh** [caffeinated/shinobi#1]
Laravel 5 supports publishing now

http://laravel.com/docs/master/packages

**Comment by kaidesu** [comment]
Yup! I'll be updating all my packages to support this soon. Thanks for the heads up! I'll close this ticket once things are updated.

**Comment by kaidesu** [comment]
Fixed with 0fd6618956839c820b69ce0b7f929f6d2a4c5d46!
