### ISSUE TITLE
Problems with sinobi D: on laravel 5.8.*

### ISSUE THREAD

**Issue by fsialer** [caffeinated/shinobi#100]
Hi, somebody to installed shinobi on laravel 5.8.*, I've problems on installation. It have not support,  can you help me?

**Comment by wehsoft** [comment]
To use this package in laravel 5.8. * Must use version 4. * of the package, it is still in trial version due to many changes!

I suggest waiting on version 5.7. * Of the same laravel, or else help complete the package changes.

> Hi, somebody to installed shinobi on laravel 5.8.*, I've problems on installation. It have not support, can you help me?

**Comment by kaidesu** [comment]
Tagged v3.4.0 with Laravel 5.8 support :+1:
