### ISSUE TITLE
Can't locate path: \vendor\caffeinated\shinobi\src/../database/migrations/>

### ISSUE THREAD

**Issue by Sierra-034** [caffeinated/shinobi#101]
When I'm trying to publish the [ShenobiServiceProvider](https://github.com/caffeinated/shinobi/blob/master/src/ShinobiServiceProvider.php) with command  
`php artisan vendor:publish --provider="Caffeinated\Shinobi\ShinobiServiceProvider"`
without `--tag="config"` option in order to publish the provided migrations files in my project I get the following error. 

`Can't locate path: project-dir\vendor\caffeinated\shinobi\src/../database/migrations/>`

**caffeinated/shinobi** downloaded by using the following command
`composer require caffeinated/shinobi`
getting the following entry in the composer.json file
`"caffeinated/shinobi": "^4.0"`

However I "fixed" the problem just by modifying the next line in the **ShenobiServiceProvider** file. 

https://github.com/caffeinated/shinobi/blob/68039b180455f8156d29cc24b48fb853fe29f6d8/src/ShinobiServiceProvider.php#L106

to

`__DIR__.'/../migrations/' => database_path('migrations'),`

But this is not a real fixation of the problem because I touched Shinobi code from my project wich is not a good practice. So I should make a pull request with that change.
Sorry about the english and thanks for reading

**Comment by underline-software** [comment]
Mi problema fue el mismo en la version laravel 5.7 con caffeinated/shinobi version 4.0 pero lo he resuelto modificando esto :

protected function publishMigrations()
    {
        $this->publishes([
                        // he quitado esto "database/migrations/" y he dejado solo "/migrations/"
            __DIR__.'/../migrations/' => database_path('migrations'),
        ],'migrations');
    }
