### ISSUE TITLE
Blade directive @can doesn´t work 

### ISSUE THREAD

**Issue by aesu** [caffeinated/shinobi#104]
Hello everybody, i'm testing permissions assigned to a role using "can" directive like this:

```
@can('incomes.index', $permissions)
    <li class="nav-item">
        <a href="{{route('incomes.index')}}" class="nav-link">Incomes</a>
    </li>
@endcan
```

But it is not working and in the cahe file shows something like this:
```
<?php if (app(\Illuminate\Contracts\Auth\Access\Gate::class)->check('incomes.index')): ?>
    <li class="nav-item">
        <a href="<?php echo e(route('incomes.index')); ?>" class="nav-link">Incomes</a>
    </li>
<?php endif; ?>
```
I really aprettiate your help, thank´s.
Note: I'm using Laravel 5.8 and Shinobbi 4.0, long time ago, i used the package 3.x in Laravel 5.5 and it worked fine, what can be the problem?. Thank's again.

**Comment by kaidesu** [comment]
Shouldn't need to pass the second parameter through - `@can('incomes.index')` should suffice here :+1:

**Comment by aesu** [comment]
@kaidesu It doesn´t work too.

**Comment by kaidesu** [comment]
And you have the `incomes.index` permission in your database? Is the permission assigned to any user role?

**Comment by aesu** [comment]
Yes, of course I do.

**Comment by SAMDEV-R** [comment]
For me isn't work too. I configure the v.4 but with the can middleware doesn't works.
