### ISSUE TITLE
Use auth()->user()->hasPermissionTo() and @can is not the same

### ISSUE THREAD

**Issue by emaw705** [caffeinated/shinobi#105]
Hi. I'm having a problem with the performance using the blade directive @can.

In a 'for' sentence I have to check the users' permissions. If I use the blade directive @can, every time Laravel do a query to database. Otherwise, if I use auth()->user()->hasPermissionTo() Laravel do not a query to database. 

Example:

(Controller)

public function index()
    {
        $offer_categories = OfferCategory::orderBy( 'id', 'ASC' )
            ->simplePaginate(2000);

        return view('offer_categories.index', compact( 'offer_categories' ));
    }

(View with auth()->user()->hasPermissionTo())

...
@foreach ($offer_categories as $category)

                <tr>
                    <th scope="row">{{ $category->id }}</th>
                    <td>{{ $category->name }}</td>
                    <td>{{ str_limit( $category->description, 150 ) }}</td>
                    <td>
                        @if( auth()->user()->hasPermissionTo( 'offer.categories.show' ) )
                            <a href="{{ route('offers.categories.show', $category ) }} "><span class="oi oi-eye" title="{{ __( 'categories.view' ) }}"></span></a>
                        @endif

                        @if( auth()->user()->hasPermissionTo('offer.categories.edit') )
                            <a href="{{ route('offers.categories.edit', $category ) }} "><span class="oi oi-pencil" title="{{ __( 'categories.edit' ) }}"></span></a>
                        @endif

                        @if( auth()->user()->hasPermissionTo('offer.categories.print') )
                            <a href="{{ route('offers.categories.print', $category ) }}" target="_blank" ><span class="oi oi-print" title="{{ __( 'categories.print' ) }}" ></span></a>
                        @endif
                    </td>
                </tr>
@endforeach
...

(Numbers of Queries) 5

(Time) 500ms

(View with @can())

...
@foreach ($offer_categories as $category)

                <tr>
                    <th scope="row">{{ $category->id }}</th>
                    <td>{{ $category->name }}</td>
                    <td>{{ str_limit( $category->description, 150 ) }}</td>
                    <td>
                        @can( 'offer.categories.show' )
                            <a href="{{ route('offers.categories.show', $category ) }} "><span class="oi oi-eye" title="{{ __( 'categories.view' ) }}"></span></a>
                        @endcan

                        @can( 'offer.categories.edit' )
                            <a href="{{ route('offers.categories.edit', $category ) }} "><span class="oi oi-pencil" title="{{ __( 'categories.edit' ) }}"></span></a>
                        @endcan

                        @if( !$category->has_products )
                            @can( 'offer.categories.destroy' )
                                <a href="{{ route('offers.categories.destroy', $category ) }} "><span class="oi oi-trash" title="{{ __( 'categories.delete' ) }}"></span></a>
                            @endcan
                        @endif

                        @can( 'offer.categories.print' )
                            <a href="{{ route('offers.categories.print', $category ) }}" target="_blank" ><span class="oi oi-print" title="{{ __( 'categories.print' ) }}" ></span></a>
                        @endcan
                    </td>
                </tr>

@endforeach
...

(Numbers of Queries) > 3000

(Time) 10000ms

How can I to use caffeinated/Shinobi for improve the performance? 
Are the permissions saved on caché?

Thanks.

**Comment by kaidesu** [comment]
Adding an experimental caching layer to v4.1.0. Please give it a try and provide feedback on your usage in 👍
