### ISSUE TITLE
Trait 'Caffeinated\Shinobi\Traits\ShinobiTrait' not found

### ISSUE THREAD

**Issue by lcarmenate1997** [caffeinated/shinobi#106]
There is no trait. I do not know what to do. You need that trait and it does not appear in the package. Without that I can not continue.

**Comment by kaidesu** [comment]
If you're using the latest version of Laravel you'd be using v4.0, which correct, does not have the `ShinobiTrait` file. Instead, you'd be using `HasRolesAndPermissions`.

https://caffeinatedpackages.com/guide/packages/shinobi.html#usage
