### ISSUE TITLE
Update requirements for Laravel 5.1

### ISSUE THREAD

**Issue by ssheduardo** [caffeinated/shinobi#11]
When update Laravel 5.0 to 5.1 not resolving requirements, in you composer.json you have:
```

"require": {
        "php": ">=5.4.0",
        "illuminate/database": "5.0.*",
        "illuminate/support": "5.0.*",
        "illuminate/filesystem": "5.0.*",
        "illuminate/config": "5.0.*"
    },
```
Please create new branch only for L5.1

![Imgur](http://i.imgur.com/sPtkymL.png?1)

**Comment by kaidesu** [comment]
This was intentional. I'll be updating all my packages for 5.1 in the coming week. Shinobi as it stands now is not compatible with 5.1.

**Comment by kaidesu** [comment]
Pull in [v2.0](https://github.com/caffeinated/shinobi/releases/tag/v2.0).
