### ISSUE TITLE
hasPermissionThroughRole() always returns true

### ISSUE THREAD

**Issue by zknulled** [caffeinated/shinobi#112]
Sorry for my bad english.

My system works before i update to the latest version (4.1), after that permissions system brokes, comparing the code of both versions i see in this version $permission variable is unused.

~~~~
protected function hasPermissionThroughRole($permission): bool
    {
        if ($this->hasRoles()) {
            foreach ($this->roles as $role) {
                if ($this->roles->contains($role)) {
                    return true;
                }
            }
        }

        return false;
    }
~~~~

And i think this need to change $this->roles for $permission->roles to work fine.

~~~~
protected function hasPermissionThroughRole($permission): bool
    {
        if ($this->hasRoles()) {
            foreach (**$permission->roles** as $role) {
                if (**$permission->roles**->contains($role)) {
                    return true;
                }
            }
        }

        return false;
    }
~~~~

**Comment by carlos3434** [comment]
not really, I think it should be as following
`        if ($this->hasRoles()) { 
            foreach ($this->roles as $role) {
                if ($role->contains($permission)) {
                    return true;
                }
            }
        }`

**Comment by zknulled** [comment]
You're right dude
