### ISSUE TITLE
 "caffeinated/shinobi": "^4.1"  Can not find the UserHasPermission file

### ISSUE THREAD

**Issue by xavi033** [caffeinated/shinobi#114]

**Comment by xavi033** [comment]
in vendor/caffeinated/shinobi/src/Middleware create a file UserHasPermissio.php 
***************************************************************************************************
<?php

namespace Caffeinated\Shinobi\Middleware;

use Caffeinated\Shinobi\Models\Role;
use Closure;
use Illuminate\Contracts\Auth\Guard;

class UserHasPermission
{
    /**
     * @var Illuminate\Contracts\Auth\Guard
     */
    protected $auth;

    /**
     * Create a new UserHasPermission instance.
     *
     * @param Guard $auth
     */
    public function __construct(Guard $auth)
    {
        $this->auth = $auth;
    }

    /**
     * Run the request filter.
     *
     * @param \Illuminate\Http\Request $request
     * @param \Closure                 $closure
     * @param array|string             $permissions
     *
     * @return mixed
     */
    public function handle($request, Closure $next, $permissions)
    {
        if ($this->auth->check()) {
            if (!$this->auth->user()->can($permissions)) {
                if ($request->ajax()) {
                    return response('Unauthorized.', 403);
                }

                abort(403, 'Unauthorized action.');
            }
        } else {
            $guest = Role::whereSlug('guest')->first();

            if ($guest) {
                if (!$guest->can($permissions)) {
                    if ($request->ajax()) {
                        return response('Unauthorized.', 403);
                    }

                    abort(403, 'Unauthorized action.');
                }
            }
        }

        return $next($request);
    }
}

**Comment by kaidesu** [comment]
This isn't required as authorization is handled through Laravel's gates natively.

Just ensure that `Illuminate\Auth\Middleware\Authorize` is assigned the `can` key in your `App\Http\Kernel` class
