### ISSUE TITLE
Laravel 5.5 problem when i migrate require Doctrine DBAL

### ISSUE THREAD

**Issue by TranceDevCode** [caffeinated/shinobi#116]
hey hello, i hope you be good...

I have a problem when make a php artisan migrate the problem star when return this message:

In ChangeColumn.php line 30:
  Changing columns for table "roles" requires Doctrine DBAL; install "doctrine/dbal".

i install the doctrine/dbal and 
later migrate again, and later return a line with a message,  

php artisan migrate
Migration table created successfully.

In AbstractPlatform.php line 423:

  Unknown database type enum requested, Doctrine\DBAL\Platforms\MySqlPlatform may not support it.

i find the problem and in the file 2015_12_04_003040_add_special_role_column.php have this line 

 public function up()
    {
        Schema::table('roles', function ($table) {
          $table->enum('special', ['all-access', 'no-access'])->nullable();
        });
    }

late change this line for a solution...

 public function up()
    {
        Schema::table('roles', function ($table) {
          $table->string('special', 10)->nullable();
        });
    }

and migrate again and now have other problem with this line.

php artisan migrate
Migration table created successfully.

In Connection.php line 664:

  SQLSTATE[HY000]: General error: 1833 Cannot change column 'id': used in a foreign key constraint 'permission_role_role_id_foreign' of table 'commonexpe
  nses.permission_role' (SQL: ALTER TABLE roles CHANGE id id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL)

In PDOStatement.php line 107:

  SQLSTATE[HY000]: General error: 1833 Cannot change column 'id': used in a foreign key constraint 'permission_role_role_id_foreign' of table 'commonexpe
  nses.permission_role'

In PDOStatement.php line 105:

  SQLSTATE[HY000]: General error: 1833 Cannot change column 'id': used in a foreign key constraint 'permission_role_role_id_foreign' of table 'commonexpe
  nses.permission_role'

i don't understand how can fix this problem now... please i need help....

i use Laravel 5.5
php 7.0.30

Thank you!

**Comment by kaidesu** [comment]
Sorry I can only support the latest version of the package, which requires Laravel 5.7+ and PHP 7.1

**Comment by TranceDevCode** [comment]
understand but the solution in my project is reinstall the package...

composer require caffeinated/sinobi version for my Laravel 5.5 

composer require caffeinated/sinobi 3.1 or 3.2 or 3.4.
now is working the migration and migrate.

Thank you @kaidesu

**Comment by kaidesu** [comment]
Interesting! Glad it all works for you now :v:
