### ISSUE TITLE
BadMethodCallException  : This cache store does not support tagging.

### ISSUE THREAD

**Issue by ASanchezT85** [caffeinated/shinobi#117]
regards

First of all, thank you in advance for the help you can give me.

I am experiencing the following problem when running the php artisan migrate --seed command
![BadMethodCallException - Shinobi](https://user-images.githubusercontent.com/10146441/62818068-9d54e180-bb0f-11e9-84d9-28ab9cbdb3b8.jpg)

In the seeder I am loading the permissions from the permissions table that will then be assigned to the roles by sight.

At first I had solved it as follows:

![BadMethodCallException - Shinobi-2](https://user-images.githubusercontent.com/10146441/62818089-f290f300-bb0f-11e9-851a-539f7994c135.jpg)

But when executing the composer update command I have to reconfigure the RefreshesPermissionCache file, I think it is not the must be, because I am touching the core of the package.

I am using:

- windows 10,
- Laragon,
- Laravel 5.8
- caffeinated / shinobi 4.1

**Comment by kaidesu** [comment]
👋 

Cache tags are not supported when using the `file` or `database` cache drivers. The package should check for this though and properly fallback and maybe warn the developer somehow.

See here for more information on cache tag support: https://laravel.com/docs/5.8/cache#cache-tags

**Comment by phoenyx12** [comment]
Thank you. I had the same problem. That is my final code.

`<?php

namespace Caffeinated\Shinobi\Concerns;

trait RefreshesPermissionCache
{
    public static function bootRefreshesPermissionCache()
    {
        static::saved(function() {
            if (config('shinobi.cache.enabled'))
            cache()->tags(config('shinobi.cache.tag'))->flush();

            else cache()->flush();
        });

        static::deleted(function() {
            if (config('shinobi.cache.enabled'))
            cache()->tags(config('shinobi.cache.tag'))->flush();
            
            else cache()->flush();
        });
    }
}`

**Comment by angeldelacruzsdo** [comment]
1. On cache.php: `'default' => env('CACHE_DRIVER', 'array'),`
2. `php artisan cache:clear && php artisan view:clear && php artisan config:cache`
Ready!

**Comment by thewebartisan7** [comment]
@phoenyx12 solution is better if we are using another cache driver in production like file or database. Otherwise we need to stay with array.

But instaed of using "tags", why not use key and then forget() ?

Almost add check if shinobi.tags is set to "null" or "false" in config and then never use "tags" to store cache.
