### ISSUE TITLE
"help wanted" 

### ISSUE THREAD

**Issue by alexeitav** [caffeinated/shinobi#12]
Hello,

Is there a way to get all users with a such role? For example, get all user with the role 'admin'?

P.S. Sorry if I am posting this in a wrong place.

Regards.
Alexei

**Comment by alexeitav** [comment]
Hello,

I founded a way...I don't know if it is the better way, but it works.

```
$admins = User::whereHas(
            'roles', function($query) {
                $query->where('slug', 'admin');
            }
        )->get();
```

**Comment by kaidesu** [comment]
No need for that. The relationship between `Users` and `Roles` is a [many-to-many relationship](http://laravel.com/docs/5.1/eloquent-relationships#many-to-many). You can easily retrieve all the users for a given role by simply fetching your role. Here's a quick example:

```php
$role = Role::find(1);

foreach ($role->users as $user) {
    //
}
```

So the example you provided in your second comment would be more like the following:

```php
$admin  = Role::where('slug', 'admin')->first();
$admins = $admin->users;
```

**Comment by alexeitav** [comment]
Thanks kaidesu. I will change it in my code.
