### ISSUE TITLE
question focused on relationships between models

### ISSUE THREAD

**Issue by dagume** [caffeinated/shinobi#122]
I am implementing this package in my project but I wish that my login is done with another table called "contacts" as I can modify so that it is not from the "user" table but from the "contacts" table

**Comment by SergioFloresG** [comment]
It depends.

If your permission logic starts, validates and / or gets from the "_contacts_" table, just add the "HasRolesAndPermissions" trait into the model.

**Comment by dagume** [comment]
Can I use the "HasRolesAndPermissions" feature on two models at the same time, how do I implement it?

**Comment by kaidesu** [comment]
You totally can :+1: It's just a simple trait that registers the necessary relationships and methods. If it doesn't work for you out of the box, you can reference it for your own model and bring the methods/relationships in yourself.
