### ISSUE TITLE
ERROR LARAVEL REQUERIMENTS

### ISSUE THREAD

**Issue by MatyJin** [caffeinated/shinobi#125]
i have a error :

> Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for caffeinated/shinobi ^5.0 -> satisfiable by caffeinated/shinobi[v5.0.0].
    - Conclusion: remove laravel/framework v5.8.28
    - Conclusion: don't install laravel/framework v5.8.28
    - caffeinated/shinobi v5.0.0 requires illuminate/support ^6.0 -> satisfiable by illuminate/support[6.x-dev, v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4].
    - don't install illuminate/support 6.x-dev|don't install laravel/framework v5.8.28
    - don't install illuminate/support v6.0.0|don't install laravel/framework v5.8.28
    - don't install illuminate/support v6.0.1|don't install laravel/framework v5.8.28
    - don't install illuminate/support v6.0.2|don't install laravel/framework v5.8.28
    - don't install illuminate/support v6.0.3|don't install laravel/framework v5.8.28
    - don't install illuminate/support v6.0.4|don't install laravel/framework v5.8.28
    - Installation request for laravel/framework (locked at v5.8.28, required as 5.8.*) -> satisfiable by laravel/framework[v5.8.28].

I USED LARAVEL 5.8

**Comment by narugamy** [comment]
Use composer require caffeinated/shinobi "^4.0"  for laravel version 5.8
