### ISSUE TITLE
problem for import users

### ISSUE THREAD

**Issue by TranceDevCode** [caffeinated/shinobi#127]
hello, thank for the package Caffeinated...

i have a problem when i try to import users from excel... return this problem 

SQLSTATE[HY000]: General error: 1364 Field 'client_id' doesn't have a default value (SQL: insert into `users` (`name`, `email`, `password`, `updated_at`, `created_at`) values ( Adolfo , email@gmail.com, $2y$10$3pddahMSRW7tws4K, 2019-11-01 12:30:19, 2019-11-01 12:30:19))

I don't know why it doesn't read the value that I have in the excel, it's a numerical value and in addition to my user model I also add client_id to the fillable ... I am using the matwebsite package to import, in all others it works fine, except in the import users ... definitely does not recognize the other fields as client_id, co-owner_id and other

Do you have any idea about this problem? thank to you

**Comment by kaidesu** [comment]
Sorry, the problem you're running into isn't related to the Shinobi package at all, so I can't help you here ✌️
