### ISSUE TITLE
Error all permissions 

### ISSUE THREAD

**Issue by narugamy** [caffeinated/shinobi#136]
Hello, I have been testing in a development the latest version with support for Laravel 7 and when it comes to bringing all the permissions of a user, it only brings me those related to the permission_user table and does not add to those of permission_role, which is causing problems for me. .
As seen in the images I have the permission_role table is full of data but it does not bring me any results but if I get to permission_user it only brings me from that table and not the permission_role data.
![image](https://user-images.githubusercontent.com/13419266/78308828-242b5400-750f-11ea-9555-8850adb2624c.png)

![image](https://user-images.githubusercontent.com/13419266/78308843-2ee5e900-750f-11ea-8fc0-4c544ac532f7.png)
![image](https://user-images.githubusercontent.com/13419266/78308855-36a58d80-750f-11ea-80a9-f787c4347db9.png)

**Comment by kaidesu** [comment]
you're trying to get permissions for both the user _and_ the role, all in one?

**Comment by narugamy** [comment]
Exactly friend, in addition to that if you use the cache of the package it is lost and it appears that I do not have any permission unless I have assigned it to the user and not to the role
