### ISSUE TITLE
Can I get the name of Role which belongs to User?

### ISSUE THREAD

**Issue by Fry4u** [caffeinated/shinobi#15]
Hi,

is it possible to get the names of the roles or permissions of the specific User?
Something like this: User::find(1)->roles() and then in foreach $role->name
Thanks for the answer.

**Comment by Fry4u** [comment]
Sorry, it was bad question...I get it right away :)

@foreach($user->roles as $role)
      {{ $role->name }}
@endforeach

**Comment by kaidesu** [comment]
:+1:
