### ISSUE TITLE
With new laravel 5.11 authorization can i still use this library?

### ISSUE THREAD

**Issue by coding-sunshine** [caffeinated/shinobi#17]
laravel 5.11 authorization has been released recently. How different is Shinobi from that, is Shinobi still relevant ?

**Comment by kaidesu** [comment]
You may certainly continue to use Shinobi. I'll still be maintaining and building Shinobi up for the foreseeable future.

However, Shinobi is _not_ compatible with Laravel's Authorization implementation (as far as the permissions and whatnot go - logging in/out/etc. is still fine per usual) - you'll need to choose one or the other.

Shinobi shares a lot of functionality that was added with Laravel's Authorization library. I don't have a complete breakdown of the differences right now, but they both provide generally the same functionality - just implemented in different ways. The only difference I can think of is Shinobi offers the ability to group your users up into various user roles out of the box (optional) on top of the ability to assign and check for permissions. Laravel's Authorization library is solely focused on permissions so you'd need to come up with a way to group users if that's a feature you wanted.

In the end though, you can consider Shinobi an alternative solution to a common problem (user permissions). And in all honesty, use whatever fits best with your application that makes sense to you.

**Comment by coding-sunshine** [comment]
Thanks, for now I would be sticking to shinobi.

**Comment by landjea** [comment]
@coding-sunshine Just be careful if you enable both the official Authorization and shinobi. The "can()" method exists in the official one so you can start getting errors because it was previously defined by Shinobi (and realistically just about every ACL / RBAC package). I still prefer shinobi but you need to be aware / careful of that catch.

**Comment by coding-sunshine** [comment]
Thanks for the suggestion. I am planning to use shinobi only not including default authorization :)

**Comment by MLenngren** [comment]
Matt on the Laravel 5.1.11 Auth: 

If you need anything like Roles, user groups, or database-defined permissions levels, you'll still need to do some of the work yourself--and you may still find yourself reaching for an external package. But for most circumstances, this is more than enough, and just as simple as it can be.

**Comment by MLenngren** [comment]
FYI: I did find an issue with the ->can method as @landjea mentioned, but it were not from Shinobi but from jenssegers MongoDB V2.2.0 (Laravel 5.1 Support). 

I have not had time to investigate, but I would guess that MongoDB package has User support and ties into the new Authorization module hence creating an issue for me when running Shinobi (I downgraded the mongoDB for now).

**Comment by kaidesu** [comment]
Seems odd for a MongoDB package to have user authorization features.
