### ISSUE TITLE
Security issue with can

### ISSUE THREAD

**Issue by MLenngren** [caffeinated/shinobi#2]
Thank you for this drugged ninja component!

I just tried it out and unless I did not set it up correctly the default behavior of the can function is set to true. If the user has no roles it will return true (as the can function only return false if a "false" role exists).

Good work though, keep it up!

**Comment by kaidesu** [comment]
Oh no!

I'll definitely get that oversight fixed. Thanks for pointing it out!

**Comment by MLenngren** [comment]
Great response time too! Thanks.

**Comment by kaidesu** [comment]
I'm going to leave this issue open until it's fixed~
