### ISSUE TITLE
Purpose of Permissions "slug"

### ISSUE THREAD

**Issue by landjea** [caffeinated/shinobi#20]
Not quite sure the purpose of the slug field in the permissions table.

Assuming I have a permission such as - 

Name|Slug|Description
-------|------|---------------
todo.create.all|tca|Can create a todo in all categories

Is that to facilitate something like 

```
if ( Auth::user()->can('tca') )
```

instead of something like 

```
if ( Auth::user()->can('todo.create.all') )
```

? Thanks.

**Comment by kaidesu** [comment]
Right - you use the `slug` when needing to reference a permission for a check. The name is for your user-friendly name within your application.

So, in your example you would have something like this:

| Name | Slug | Description |
|------|------|-------------|
| Create All Todo | todo.create.all | Can create a todo in all categories. |

And when needing to check for the permission, you'd reference the `slug`:

```php
if (Auth::user()->can('todo.create.all') {
    //
}
```

**Comment by landjea** [comment]
Fantastic. Thanks for the quick response. You should probably cut/paste your response directly into your usage page. Very helpful. :)

**Comment by kaidesu** [comment]
No problem, and I'll certainly get the usage and some other documentation updated here shortly!

:+1:
