### ISSUE TITLE
Trait collision in Laravel 5.1

### ISSUE THREAD

**Issue by dericcain** [caffeinated/shinobi#21]
I am getting an error in Laravel 5.1:

`Trait method can has not been applied, because there are collisions with other trait methods on App\User`

I am using Shinobi 2.2. How do I fix this?

**Comment by kaidesu** [comment]
You'll need to get rid of the `Authorizable` trait in your User model.

See here for more information: https://github.com/caffeinated/shinobi/issues/17

**Comment by dericcain** [comment]
Got it! Thank you.
