### ISSUE TITLE
...intended? No-access "bug"?

### ISSUE THREAD

**Issue by landjea** [caffeinated/shinobi#22]
I thought that a "no-access" would over-ride all other permissions. However, if there are two roles on a user, and one is no-access and the other is "allow", the allow will permit the user to continue.

Is that intended that for a "no-access" role to work all other roles have to be removed as well?

Just curious, thanks.

**Comment by kaidesu** [comment]
Indeed is a bug - the special role attributes are meant to be a "master override" regardless of the manually assigned permissions/roles. Thanks for bringing this up I'll be sure to get this patched soon.

**Comment by kaidesu** [comment]
Patched in v2.2.1!

Let me know if you have any further issues~

**Comment by landjea** [comment]
Fantastic, thanks.
