### ISSUE TITLE
Blade directive @can non-functional.

### ISSUE THREAD

**Issue by landjea** [caffeinated/shinobi#23]
Using blade, the @can directive doesn't seem to be functional. The generated code uses `Gate::` instead of `Shinboi::`

```@if ( \Shinobi::can() )``` works fine.

I removed the Authorizable lines from User model and the @role directive is working fine as well.

welcome.blade.php

                @can('dddd')
                    Can Test
                @endcan

                @role('first')
                    Role Test
                @endrole

laravel_generated_cache

                <?php if (Gate::check('dddd')): ?>
                    Can Test
                <?php endif; ?>

                <?php if (\Shinobi::is(('first'))): ?>
                    Role Test
                <?php endif; ?>

Sorry for the extra activity for you tonight. I am just about finished the front-end dashboard package I am working on for Shinobi and want to finish it off. Thanks.

**Comment by kaidesu** [comment]
Oh, seems like the provided Auth provider with Laravel is still registered. If you remove `App\Providers\AuthServiceProvider::class,` from your `config/app.php` file under the providers key I believe you'll be good to go.

**Comment by landjea** [comment]
Ok. I like the Auth provided methods so I will stick with Shinobi::can
instead. Thanks. Feel free to close this.

**Comment by kaidesu** [comment]
I don't think it gets rid of the Auth facade or methods - I'll have to double check when I'm at my computer but I'm pretty sure I don't have that provider registered in my applications.

**Comment by kaidesu** [comment]
Yup, can confirm - you'll be fine removing `App\Providers\AuthServiceProvider::class` from your app config file. Won't lose `Auth` capabilities or anything - will just prevent conflicts with the `can` Blade directive~

**Comment by Nekudapsik** [comment]
After removing AuthServiceProvider class from config, @can still non-functional.

**Comment by landjea** [comment]
Hi @Nekudapsik. Which version of Laravel are you using? Did you add the ShinobiTrait to your User model? What is generated when you try to use the @can method?

**Comment by Nekudapsik** [comment]
Hey @landjea . I am using laravel v5.1 and yes i've added ShinobiTrait to my user model,

```php
<?php if (Gate::check('edit.report.other')): ?>
<th rowspan="2" data-sortable="false" data-searchable="false">Action</th>
<?php endif; ?>
```
and thats what i get when i use @can method.

**Comment by landjea** [comment]
Thanks @Nekudapsik sorry for asking the basics, don't mean to offend.

By seeing that `Gate::check` it means that it is still using Laravel's default auth. 

Did you also remember to comment away the three instances of Authorizable when you added Shinobi?

The User model on your app should look (roughly) like this :

```
<?php

namespace App;

use Caffeinated\Shinobi\Traits\ShinobiTrait;
use Illuminate\Auth\Authenticatable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Auth\Passwords\CanResetPassword;
//use Illuminate\Foundation\Auth\Access\Authorizable;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
//use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;

class User extends Model implements AuthenticatableContract,
                                   // AuthorizableContract,
                                    CanResetPasswordContract
{
    use Authenticatable, CanResetPassword, ShinobiTrait; //Authorizable
```

**Comment by Nekudapsik** [comment]
Not offended. That's how my model looks like and the effect is still the same:

```php
use Illuminate\Auth\Authenticatable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;
use McCool\LaravelAutoPresenter\HasPresenter;
use Illuminate\Database\Eloquent\SoftDeletes;
use Caffeinated\Shinobi\Traits\ShinobiTrait;

class User extends Model implements AuthenticatableContract,
                                    CanResetPasswordContract,
                                    HasPresenter
{
    use Authenticatable, CanResetPassword, SoftDeletes, ShinobiTrait;
```

**Comment by landjea** [comment]
Hi again @Nekudapsik. I see that you still have the AuthServiceProvider defined in your config/app.php file. Above, @kaidesu noted that 

> Oh, seems like the provided Auth provider with Laravel is still registered. If you remove App\Providers\AuthServiceProvider::class, from your config/app.php file under the providers key I believe you'll be good to go. 

I wanted the AuthServiceProviders other functions so I stopped at this point, however, @kaidesu continues on later with a test of his own :

> Yup, can confirm - you'll be fine removing App\Providers\AuthServiceProvider::class from your app config file. Won't lose Auth capabilities or anything - will just prevent conflicts with the can Blade directive~

So that is probably the step you want to take next.

Good luck! :)
