### ISSUE TITLE
Front end pages. (GUI)

### ISSUE THREAD

**Issue by landjea** [caffeinated/shinobi#24]
Not sure if I mentioned this properly before but I have been putting together a frontend "dashboard" for  Shinobi. Alpha release is out if you want to see it and tell me to rip your name the hell off of it. :smile:

https://github.com/SmarchSoftware/watchtower

Anyway, the docs are under construction but the install works as explained. Going to get the config options, roles / permissions pages up on the wiki shortly.

Probably said it before but, thanks again for the package.

**Comment by kaidesu** [comment]
No way man, this is bad ass! I'll have to check this out later today - keep up the good work!

**Comment by landjea** [comment]
Thanks!

No problem. I will be using Shinobi instead of my old RBAC package as I move more and more sites to L5 so I figured I would need this over and over again. I hope to have the other docs done soon _(holiday timing right?)_ but it should be pretty "click and go" without the docs anyway once it is set up.

**Comment by kaidesu** [comment]
Very nice. Would you mind I linked to this within the readme for shinobi?

**Comment by landjea** [comment]
Not at all. Encourages me to finish docs faster. :)

**Comment by kaidesu** [comment]
Done. Awesome work, keep it up!
