### ISSUE TITLE
Usage for Laravel 5.2

### ISSUE THREAD

**Issue by frankiecmk** [caffeinated/shinobi#25]
Is there any usage guide for Laravel 5.2 ? 
https://github.com/caffeinated/shinobi/wiki/Usage

**Comment by landjea** [comment]
Laravel 5.2 can be used with the instructions provided on the page you referenced. The newer user model in Laravel 5.2 is much shorter but as long as you use the Laravel 5.1 model info on that page, Shinobi will work on Laravel 5.2 without any loss of functionality for Laravel or Shinobi.

**Comment by gbrock** [comment]
Found one issue with 5.2: Laravel overrides Shinobi's `@can` Blade directive.  Meaning, it gets turned into 5.2's new `Gate::check` instead of `Shinobi::can`.

**Comment by gmill20** [comment]
is it possible to use multi Roles in Shinobi?

example... would this work?

                             @role(['admin', 'advisor'])
                                I am an Admin & advisor User
                            @else
                            @endrole
