### ISSUE TITLE
Laravel 5.2 Trait error.

### ISSUE THREAD

**Issue by landjea** [caffeinated/shinobi#26]
Kinda ties into #25 earlier.

On a fresh install of Laravel 5.2 and using the Shinobi trait, throws this error : 

```
ErrorException in User.php line 9:
Declaration of Caffeinated\Shinobi\Traits\ShinobiTrait::can($permission) should be compatible with Illuminate\Foundation\Auth\User::can($ability, $arguments = Array)
```

A simple fix, of course is to just add `, $arguments = [])` inside the can function of ShinobiTrait...but there is a number of other "can" calls that are affected _(I think)_ throughout the package. I had started a PR with the changes but I have hesitations of modifying the __call function in ShinobiTrait since you are already passing in an arguments parameter so I thought I better go with this issue instead...

**Comment by landjea** [comment]
FYI - Changing line 132, 145 and 207 of ShinobiTrait.php to reference the arguments array haven't shown any negative affects yet. Still testing though.

**Comment by kaidesu** [comment]
Shinobi is not compatible with the authorization methods included with Laravel 5.2. Have to choose one over the other.

Within your user model, take out the call to the `Authorizable` trait provided by Laravel and you'll be good to go~

I'll be sure to update the usage docs with notes on this.

**Comment by landjea** [comment]
Thanks. Yeah, I am aware it is one or the other but there is no authorizable trait defined in App\User in Laravel 5.2. For some reason they decided to bury it way down in Illuminate. (https://github.com/laravel/framework/blob/5.2/src/Illuminate/Foundation/Auth/User.php - if you are curious) So out of the box, it won't work with the usage instructions. I found that passing in the arguments array on the 3 lines mentioned above as fixing it so it works out of the box again. That was all. Thanks.

**Comment by ravloony** [comment]
I think you would do better to make your User like this:

    <?php namespace App;

    use Illuminate\Auth\Authenticatable;
    use Illuminate\Database\Eloquent\Model;
    use Illuminate\Auth\Passwords\CanResetPassword;
    use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
    use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;
    class User extends Model implements
        AuthenticatableContract,
        CanResetPasswordContract
    {
        use Authenticatable, CanResetPassword;
    }

instead of extending the official User model.

**Comment by landjea** [comment]
Thanks for the input @ravloony but...I don't see where you are referencing Shinobi anywhere there so I am not sure how it would help with making it 5.2 compatible. If you could explain what you mean that would be great. Simply adding the ShinobiTrait to the default L5.1 User model works fine and adding the ShinobiTraitto the default L5.2 User Model supplied with laravel also works fine if I make the changes I reference. Thanks again!

**Comment by ravloony** [comment]
Sorry, I wasn't clear.

Basically, the default L5.2 User model is the default L5.1 User model with the L5.2 Authorizable trait added in, which you then more or less override by adding the Shinobi Trait. So I was suggesting to simply use the L5.1 user model, as you were before, to avoid conflicts. No need to change the Shinobi code.

**Comment by landjea** [comment]
Oh okay I get what you are saying now. (kinda) You say default User model but I am not sure if you mean App/User.php (which I consider and reference as the default) or you mean the vendor supplied one (which I wasn't talking about because I don't change vendor code). So it might just be terminology we are using that is borking me around. 

Are you talking about the App/User or Vendor/../User?

Here is the new L5.2 default app/user model _(from https://github.com/laravel/laravel/blob/master/app/User.php)_ which hides away the Authorizable trait deep in the vendor/Illuminate folder.

```
<?php
namespace App;
use Illuminate\Foundation\Auth\User as Authenticatable;
class User extends Authenticatable
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];
    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}
```

So if I understand you correctly, if I replace this with the L5.1 version that I use, it will function as it did previously? _(Sorry, I am not able to test for another couple hours or so, so I am just curious if I correctly understand what you are saying....)_

**Comment by landjea** [comment]
Got a chance to test. :smile:

_So, for anyone else actually following along:_  by using the same L5.1 user model (App/User.php) that worked on Shinobi in the Laravel 5.1 world on a fresh new install of L5.2's user model (App/User.php) Shinobi is now functional again.

Also, comparing the L5.2 Vendor/.../User.php copy with the L5.1 App/User copy I am substituting, there is no loss of functionality that is expected. All the same Traits and Classes are "use"d still.

Thanks for your time and assistance @ravloony

**Comment by kaidesu** [comment]
You guys are awesome~ Pretty sure the wiki here is open to the public, so feel free to make adjustments as you see fit. I'll try and find some time soon to update the docs otherwise.

**Comment by ravloony** [comment]
@landjea, @kaidesu Glad to help, and that you're sorted out!
