### ISSUE TITLE
Just wondering how shinobi adds to 5.2.x

### ISSUE THREAD

**Issue by illuminate3** [caffeinated/shinobi#29]
Just wondering how shinobi adds to 5.2.x or has 5.2.x started to take on a maority of what shinobi started as?

**Comment by landjea** [comment]
From what I can see from the Laravel 5.2 documentation Shinobi still adds the same value in Laravel 5.2 that it added to Laravel 5.1. Laravel still doesn't have the "roles" ability (or association between roles and permissions) of Shinobi. Nor does it have the "all-access" or the "no-access" options as far as I can tell. 

So packages like Shinobi _(and Bouncer, Sentry, Entrust, etc...)_ still offer a needed value to Laravel 5.2.

**Comment by gmill20** [comment]
I'm using Shinobi with Larvarel 5.2.

Don't suppose you have an idea how to check for multiple roles? 

 @role('advisor') 

I want to do multiple checks...  @role('advisor', 'admin')  
However this throws an error.
