### ISSUE TITLE
It's possible to change the name of tables and columns ?

### ISSUE THREAD

**Issue by ricardovigatti** [caffeinated/shinobi#30]
I'm working on a new application with a legacy database and i already have tables populated to manage roles and permissions.

**Comment by landjea** [comment]
There is no config file for that (yet) but as a workaround you could change the `$table = 'roles''` and `$table="permissions"` variables in the `vendor\caffeinated\shinobi\src\models\Role.php` and `vendor\caffeinated\shinobi\src\models\Permission.php` files to match your legacy table names.

**Comment by landjea** [comment]
Just a quick note : if you do specify your own tables, you need to make sure they have the necessary fields, most notably the`slug` field for the `can`, `canAtLeast` and `role` methods all compare against the slug field. The `special` field on the role model, as well, for the "no-access" and "all-access" options.

**Comment by ricardovigatti** [comment]
Thank you. I'll try to extend some things and change some behaviors. 

Congratulations for the package.
