### ISSUE TITLE
Deny permissions

### ISSUE THREAD

**Issue by antoniopaisfernandes** [caffeinated/shinobi#32]
There should be an option to deny a permission to a user. That way, a user that has a Role with X permissions, could have a specific permission(s) denied from that X without the need to fork the Role.

Best regards,
António Fernandes

**Comment by showcheap** [comment]
@antoniopaisfernandes  
It's like

```
@cannot('access.dashboard')
    Access Dennied for {{user}}
@endcannot
```
?
