### ISSUE TITLE
Laravel 5.2.21 Fresh install + migration, then migrate:refresh or rollback gives migrator error

### ISSUE THREAD

**Issue by ryanaddams** [caffeinated/shinobi#34]
This is on a fairly fresh install.

$ artisan migrate:install
Migration table created successfully.

$ artisan migrate
Migrated: 2014_10_12_000000_create_users_table
Migrated: 2014_10_12_100000_create_password_resets_table
Migrated: 2015_01_20_084450_create_roles_table
Migrated: 2015_01_20_084525_create_role_user_table
Migrated: 2015_01_24_080208_create_permissions_table
Migrated: 2015_01_24_080433_create_permission_role_table
Migrated: 2015_12_04_003040_add_special_role_column
Migrated: 2016_02_05_192457_create_sessions_table
Migrated: 2016_02_22_152810_create_cache_table

$ artisan migrate:refresh
PHP Fatal error:  Class 'AddSpecialRoleColumn' not found in vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php on line 336

**Comment by dvwzj-smcl** [comment]
first I got this problem too and then
I just type:
`composer dump-autoload`
then it resolved.
