### ISSUE TITLE
Role Levels

### ISSUE THREAD

**Issue by johannesschobel** [caffeinated/shinobi#36]
Dear Shinobi Team,
I have a problem with my application which uses your awesome shinobi package:

I would like to have a feature like `role levels`. Consider the following example in order to clarify this feature:
I have an API endpoint, which may be accessed by the following roles: `editor`, `manager` and `admin`. In order to secure the endpoint, i need to _enable_ the endpoint for these specific roles.

However, this results in either:
1. assigning the rules `editor`, `manager` and `admin` to the route to be protected
2. assigning all of these rules to one specific `user`.

Would it be possible to create some sort of `role hierarchy` using an additional `level` attribute? (the default level would be `1`). For example, the roles listet below should become more powerful with each step:
`guest (level 1)` > `user (level 2)` > `editor (level 3)` > `manager (level 4)` > `admin (level 5)`.

Then we could use a function like this:

``` php
if($user->hasLevel() > 4) {
   // this logic is accessible for users with role manager OR admin.
   // would be similar to
   // if($user->isAdmin() || $user->isManager())
}
```

I hope you understand my problem..
Cheers from Germany,
Johannes

**Comment by kaidesu** [comment]
Why don't you create a permission for the specific API endpoint? That permission could then be assigned to any given role to give them access.

**Comment by johannesschobel** [comment]
Yeah, but if I have many endpoints to be secured in this way, this results in a huge mess of `permissions`, right? Would it be possible to add this feature?

**Comment by miranrasulian** [comment]
@johannesschobel You may add an integer column for `level` and give it 1 by default.
then create a method in your User's model to check the user's level:

```php
public function level()
{
    $roles = $this->roles()->get();

    return ($role = $roles->sortByDesc('level')->first()) ? $role->level : 0;
}
```

@kaidesu If this code is okay and you would like, I create a PR for it. but as `ShinobiTrait::getRoles()` will return an array of `slug` so I can't use it for something like this:

```php
 return ($role = $this->getRoles()->sortByDesc('level')->first()) ? $role->level : 0;
```
