### ISSUE TITLE
When there coould be Laravel 5.3 support

### ISSUE THREAD

**Issue by roulendz** [caffeinated/shinobi#37]
When there could be added Laravel 5.3 support? 
Thanks!

**Comment by roulendz** [comment]
Hello, anybody here? :)

When there could be added Laravel 5.3 suport?

Would be really grate to kicksaralready projects with 5.3.

Thanks!

**Comment by kaidesu** [comment]
Soon!

**Comment by roulendz** [comment]
That is really Awesome!
Thanks!

**Comment by showcheap** [comment]
It's now support laravel 5.3, cool 🎉 🎉

**Comment by kaidesu** [comment]
Indeed~
