### ISSUE TITLE
Laravel 5.2.45 Installation Error

### ISSUE THREAD

**Issue by bretvanhorn** [caffeinated/shinobi#40]
Hi, not sure if anyone else has had this issue, but when trying to require this package through composer, I am getting the below output. I am running 5.2.45 on a local dev environment under Valet on my Macbook Pro. Any suggestions would be welcome.

composer require caffeinated/shinobi
Using version ^3.0 for caffeinated/shinobi                           
./composer.json has been updated
Loading composer repositories with package information                                                                                    Updating dependencies (including require-dev)         Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove laravel/framework v5.2.45
    - Conclusion: don't install laravel/framework v5.2.45
    - caffeinated/shinobi 3.0.x-dev requires illuminate/config 5.3.* -> satisfiable by illuminate/config[5.3.x-dev, v5.3.0, v5.3.4].
    - caffeinated/shinobi v3.0 requires illuminate/config 5.3.* -> satisfiable by illuminate/config[5.3.x-dev, v5.3.0, v5.3.4].
    - caffeinated/shinobi v3.0.1 requires illuminate/config 5.3.* -> satisfiable by illuminate/config[5.3.x-dev, v5.3.0, v5.3.4].
    - caffeinated/shinobi v3.0.2 requires illuminate/config 5.3.* -> satisfiable by illuminate/config[5.3.x-dev, v5.3.0, v5.3.4].
    - caffeinated/shinobi v3.0.3 requires illuminate/config 5.3.* -> satisfiable by illuminate/config[5.3.x-dev, v5.3.0, v5.3.4].
    - don't install illuminate/config 5.3.x-dev|don't install laravel/framework v5.2.45
    - don't install illuminate/config v5.3.0|don't install laravel/framework v5.2.45
    - don't install illuminate/config v5.3.4|don't install laravel/framework v5.2.45
    - Installation request for laravel/framework (locked at v5.2.45, required as 5.2.*) -> satisfiable by laravel/framework[v5.2.45].
    - Installation request for caffeinated/shinobi ^3.0 -> satisfiable by caffeinated/shinobi[3.0.x-dev, v3.0, v3.0.1, v3.0.2, v3.0.3].

**Comment by kaidesu** [comment]
v3.x is only for Laravel 5.3+

You will need to install v2.x for Laravel 5.2.
