### ISSUE TITLE
laravel 5.3 @role fails

### ISSUE THREAD

**Issue by ThePoet444** [caffeinated/shinobi#43]
If I try @can() in my blade template. It works just fine. Trying @role('admin') gives me this error:

```
Type error: Argument 1 passed to Illuminate\Database\Eloquent\Model::is() must be an instance of Illuminate\Database\Eloquent\Model, string given, called in /home/vagrant/Code/rs53/vendor/caffeinated/shinobi/src/Shinobi.php on line 77 (View: /home/vagrant/Code/rs53/resources/views/home.blade.php)
```

I am using "caffeinated/shinobi": "^3.0", in my composer file. All instructions followed as well. I'm sure I borked something, I just can't figure out what.

**Comment by ThePoet444** [comment]
changing line 77 of Shinobi.php to isRole() solved the issue. Not sure if this was the preferred way of handling it, but it works.

**Comment by bretto36** [comment]
Yes, this just went out in a PR 3 days ago. Should all be good now
