### ISSUE TITLE
Is there some clever way to add permission to user?

### ISSUE THREAD

**Issue by roulendz** [caffeinated/shinobi#46]
I was wondering, is there some easy way to add permissions to specific user, not just roles.

For now if I need, to give some user some specific permission, I make new role, just for that user.
But it is not to smart :D

Maybe some one have some suggestions?

**Comment by NassimRehali15** [comment]
It's possible in Bican package

**Comment by roulendz** [comment]
Ehh, I have fully implemented this package and using watchtower - gui :)
maybe with time there will come some update to address this :)

**Comment by kaidesu** [comment]
Reasonable request - I'll add it to the list to get implemented~

**Comment by roulendz** [comment]
@kaidesu thetas awesome :) Thanks
