### ISSUE TITLE
Is this normal to have so many queries?

### ISSUE THREAD

**Issue by roulendz** [caffeinated/shinobi#47]
I have 7 rolaes and 70 premissions,

But when I open page, I have lot of queries, regarding, roles, why it is 
[Image](https://failiem.lv/u/e3hzzg22#/view/role.png)
Thanks1

**Comment by kaidesu** [comment]
I'm not able to view your image, would you mind attaching it to your issue here on GitHub? Thanks!

**Comment by roulendz** [comment]
Maybe now

https://fv8.failiem.lv/thumb_show.php?i=axy44sxx&view

**Comment by kaidesu** [comment]
Thanks, I will definitely be taking a look into this~

**Comment by paulghz** [comment]
Same thing here, it seems that every permission test creates a query. In lots of situations, we only check permissions for the authenticated user, maybe you could query everything needed (every role and permission for the user) and then save it in a var for the next uses in the same page/request ?

**Comment by kaidesu** [comment]
@roulendz and @paulghz please give v3.0.6 a spin! Should no longer see hundreds of DB queries being ran.

**Comment by paulghz** [comment]
Great ! Definitely better and efficient now !
Thank you, for this modification and your library !
