### ISSUE TITLE
After update @endcanatleast do not work

### ISSUE THREAD

**Issue by roulendz** [caffeinated/shinobi#50]
After update all my @endcanatleast statements do not work any more

All menu itemas are hidden

```
@canatleast(['edit.event', 'create.event'])
<li class="{{set_active('schedule')}}">
<a href="{{ action('EventController@index') }}">
{{tr("b/sidebar-right.reserve-lessons","Reserve lessons")}}
</a>
</li>
@endcanatleast
@canatleast(['show.event.index'])
<li class="{{set_active('appointments')}}">
<a href="/appointments">
{{tr("b/sidebar-right.open-lessons","Open all lessons")}}
</a>
</li>
@endcanatleast
```

All menus are hidden, eaven for admin.

**Comment by kaidesu** [comment]
Odd. I will look into this today.

Thanks for the report!

**Comment by roulendz** [comment]
@kaidesu So I downgraded to  caffeinated/shinobi (v3.0.5) 

And all went to normal!

Huu!!
Let me know, when you are able to fix, so I can update!

Thanks a lot, for this awesome package!

Can't wait for user premision enchantment, that will be awesome!
