### ISSUE TITLE
Trait Usage issue, 

### ISSUE THREAD

**Issue by dflow** [caffeinated/shinobi#51]
i get:
ErrorException in Model.php line 3093: Argument 1 passed to Illuminate\Database\Eloquent\Model::is() must be an instance of Illuminate\Database\Eloquent\Model, string given,

when using:
$user = User::first(); return $user->is('administrator');

I added the use ShinobiTrait; to the User.php Model

**Comment by xciser77** [comment]
i have the same problem within my app. I tried to check is a user has a role with $user->is('admin')
and get the same error as above

**Comment by xciser77** [comment]
fixes this by using $user->isRole() instead of $user->is()

**Comment by kaidesu** [comment]
Correct - with the recent addition of authorization policies to Laravel, we can no longer use the `is` method - it has been updated to `isRole`. The documentation has been updated to reflect this.
