### ISSUE TITLE
Warning: 1265 Data truncated for column 'special' at row 1

### ISSUE THREAD

**Issue by xciser77** [caffeinated/shinobi#55]
I am using this package in a laravel 5.3 project, but have a problem with the roles. When I create (or edit) a role and do not select a special access I get the errror Warning: 1265 Data truncated for column 'special' at row 1

Also when I try to edit the table in phpmyadmin I get an error when I try to edit the special role. Also when I only chose edit and change nothing I get #1064 - You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '0) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL' at line 1

**Comment by xciser77** [comment]
I fixed it. Its a laravel issue I think. It returns an empty string instead of a null value

**Comment by kaidesu** [comment]
👍
