### ISSUE TITLE
using with multiselect

### ISSUE THREAD

**Issue by illuminate3** [caffeinated/shinobi#6]
HI,
$role->getPermissions() gets the permissions per role but I'm trying to populate a multiselect and was wondering if there is method to do this?

I'm looking at using this http://loudev.com/#project for displaying the permissions.

**Comment by kaidesu** [comment]
Not as part of the package, no. Retrieving permissions for any given role will return a `Collection`, which you can do all sorts of crazy cool things with - I think you'd want to make use of the [`list`](http://laravel.com/api/5.0/Illuminate/Support/Collection.html#method_lists) method.

So something like:

```php
$role->permissions->lists('id')
```

should pull just the IDs of permissions for the role, which you can then use to determine which permissions should be selected in your multiselect.

Hope this helps!

**Comment by illuminate3** [comment]
Thanks! That got me thinking and I learned not to nest foreach loops. Ugh, double output ... lol

Here's what I did.
```
@foreach ($allPermissions as $key => $value)
	@if (isset($permissions[$key]) )
		<option value='{{ $key }}' selected>{{ $value }}</option>
	@else
		<option value='{{ $key }}'>{{ $value }}</option>
	@endif
@endforeach
```
$permissions = those sent back from Shinobi
$allPermissions = All possible permissions

Embarrassed to say but that took me a while :sob:

**Comment by kaidesu** [comment]
That looks beautiful!

**Comment by illuminate3** [comment]
Thanks ... I still don't want to admit how long those 7 lines of code took me. :relaxed:  

Really appreciate that you're putting up with me :smile:
