### ISSUE TITLE
'Call to a member function isRole() on null' when using middleware and not logged in

### ISSUE THREAD

**Issue by peterplant88** [caffeinated/shinobi#60]
I'm getting error:

> FatalErrorException in UserHasRole.php line 36: 
> Call to a member function isRole() on null

When using middleware for example:

```
Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => 'roleshinobi:admin'], function() {
    Route::get('/', 'AdminController@index');
});
```

when I'm not logged in already. Shouldn't this just be redirecting to login?

Thanks,

**Comment by SergeyMiracle** [comment]
Why not use `'auth' => \Illuminate\Auth\Middleware\Authenticate::class` middleware?

```
Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => ['roleshinobi:admin', 'auth']], function() {
    Route::get('/', 'AdminController@index');
});
```

**Comment by kaidesu** [comment]
Shinobi doesn't handle redirects - as @SergeyMiracle mentioned, you'll want to pair it with the `auth` middleware if your user needs to be logged in.
