### ISSUE TITLE
Is there any plan to merge with Laravel Model Policy object?

### ISSUE THREAD

**Issue by nafiesl** [caffeinated/shinobi#68]
Hi, first of all, thank you for this package, i'ts pretty helpfull for end users.

Just want to ask, is there any plan to merge this package with existing Laravel **model policy** object?  Especially on `ShinobiTrait@can` method (since it overrides Laravel `Authorizable@can` method).

I think Laravel model policy was really good for **fixed** user permission or authorization. But it cannot be used together.

Thanks.

**Comment by kaidesu** [comment]
I do want to merge the two for sure, just don't have a timeframe on the update. I'm always open to pull requests!

**Comment by nafiesl** [comment]
OK, thank you for the info.
