### ISSUE TITLE
Version 3.1 introduced automatic migrations

### ISSUE THREAD

**Issue by tomvo** [caffeinated/shinobi#69]
I've written in this in the original commit as well, as of version 3.1 the plugin is executing it's migrations along the global `artisan:migrate` command. This breaks with the original functionality of publishing the migrations and pick and choose what you need. 

In our scenario this breaks our codebase since we're using the original published migrations in modified form since we already had a `roles` table in our database. When upgrading to 3.1 you will get a `roles table already exists` because of this.

**Comment by tomvo** [comment]
@kaidesu Any idea on this? I can get you a PR if you let me know what your preferred way of doing this is? Adding table exists logic maybe?

**Comment by kaidesu** [comment]
Sorry for the delay on this! An update to the migrations to check for the existence of the tables I think would be the easiest route, since running package migrations is now the default action with Laravel (https://laravel.com/docs/5.5/packages#migrations).

A PR would be welcome for sure 👍

**Comment by tomvo** [comment]
@kaidesu see here https://github.com/tomvo/shinobi/commit/f88dddc3bd4d035e2113d23248a5f9270c6ffef4. This solves the issue but I'm not sure if you might want to add a notification/message somewhere so that the user is informed if a necessary table is skipped. I'm not really happy anyway with the L5.4 move to load migrations automatically like this but so it goes.
