### ISSUE TITLE
Error when dont have any role

### ISSUE THREAD

**Issue by Alvarz** [caffeinated/shinobi#72]
Hello guys, after update, if I try to use the `can` method with a user who hasn't any role it will return that error `Relationship method must return an object of type Illuminate\Database\Eloquent\Relations\Relation`, that didn't happen before update, I were using  `"version": "v3.0.10",` without problems, it's now on  `"version": "v3.1.1",`. according to my `composer.lock` file

Sorry my terrible english, Cheers!

**Comment by canaryblack** [comment]
I have the same problem but I return this error
(3/3) ErrorException
Class 'Shinobi' not found (View: F:\Software\Ampps\www\Project\resources\views\layouts\app.blade.php) (View: F:\Software\Ampps\www\Project\resources\views\layouts\app.blade.php)
