### ISSUE TITLE
Hi i'm problem instalations with laravel 5.6.11

### ISSUE THREAD

**Issue by thavoo** [caffeinated/shinobi#73]
Hello I have problems installing this package in the version of laravel 5.6.11 the problem that is presented is the following:

`composer require caffeinated/shinobi
Using version ^3.1 for caffeinated/shinobi
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install caffeinated/shinobi v3.1.1
    - Conclusion: remove laravel/framework v5.6.11
    - Installation request for caffeinated/shinobi ^3.1 -> satisfiable by caffeinated/shinobi[v3.1, v3.1.1].
    - Conclusion: don't install laravel/framework v5.6.11
    - caffeinated/shinobi v3.1 requires illuminate/config 5.3.*|5.4.*|5.5.* -> satisfiable by illuminate/config[5.3.x-dev, 5.4.x-dev, 5.5.x-dev, v5.3.0, v5.3.16, v5.3.23, v5.3.4, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39].
    - don't install illuminate/config 5.3.x-dev|don't install laravel/framework v5.6.11
    - don't install illuminate/config 5.4.x-dev|don't install laravel/framework v5.6.11
    - don't install illuminate/config 5.5.x-dev|don't install laravel/framework v5.6.11
    - don't install illuminate/config v5.3.0|don't install laravel/framework v5.6.11
    - don't install illuminate/config v5.3.16|don't install laravel/framework v5.6.11
    - don't install illuminate/config v5.3.23|don't install laravel/framework v5.6.11
    - don't install illuminate/config v5.3.4|don't install laravel/framework v5.6.11
    - don't install illuminate/config v5.4.0|don't install laravel/framework v5.6.11
    - don't install illuminate/config v5.4.13|don't install laravel/framework v5.6.11
    - don't install illuminate/config v5.4.17|don't install laravel/framework v5.6.11
    - don't install illuminate/config v5.4.19|don't install laravel/framework v5.6.11
    - don't install illuminate/config v5.4.27|don't install laravel/framework v5.6.11
    - don't install illuminate/config v5.4.36|don't install laravel/framework v5.6.11
    - don't install illuminate/config v5.4.9|don't install laravel/framework v5.6.11
    - don't install illuminate/config v5.5.0|don't install laravel/framework v5.6.11
    - don't install illuminate/config v5.5.16|don't install laravel/framework v5.6.11
    - don't install illuminate/config v5.5.17|don't install laravel/framework v5.6.11
    - don't install illuminate/config v5.5.2|don't install laravel/framework v5.6.11
    - don't install illuminate/config v5.5.28|don't install laravel/framework v5.6.11
    - don't install illuminate/config v5.5.33|don't install laravel/framework v5.6.11
    - don't install illuminate/config v5.5.34|don't install laravel/framework v5.6.11
    - don't install illuminate/config v5.5.35|don't install laravel/framework v5.6.11
    - don't install illuminate/config v5.5.36|don't install laravel/framework v5.6.11
    - don't install illuminate/config v5.5.37|don't install laravel/framework v5.6.11
    - don't install illuminate/config v5.5.39|don't install laravel/framework v5.6.11
    - Installation request for laravel/framework (locked at v5.6.11, required as 5.6.*) -> satisfiable by laravel/framework[v5.6.11].

Installation failed, reverting ./composer.json to its original content.
`

**Comment by gditizio** [comment]
hello, the same problem as @thavoo

**Comment by kaidesu** [comment]
v3.2 has been tagged with Laravel 5.6 support~
