### ISSUE TITLE
Don't install caffeinated/shinobi v3.1.1 in Laravel 5.6.12

### ISSUE THREAD

**Issue by JoelCL** [caffeinated/shinobi#74]
Error:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install caffeinated/shinobi v3.1.1
    - Conclusion: remove laravel/framework v5.6.12
    - Installation request for caffeinated/shinobi ^3.1 -> satisfiable by caffeinated/shinobi[v3.1, v3.1.1].
    - Conclusion: don't install laravel/framework v5.6.12
    - caffeinated/shinobi v3.1 requires illuminate/config 5.3.*|5.4.*|5.5.* -> satisfiable by illuminate/config[5.3.x-dev, 5.4.x-dev, 5.5.x-dev, v5.3.0, v5.3.16, v5.3.23, v5.3.4, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39].
    - don't install illuminate/config 5.3.x-dev|don't install laravel/framework v5.6.12
    - don't install illuminate/config 5.4.x-dev|don't install laravel/framework v5.6.12
    - don't install illuminate/config 5.5.x-dev|don't install laravel/framework v5.6.12
    - don't install illuminate/config v5.3.0|don't install laravel/framework v5.6.12
    - don't install illuminate/config v5.3.16|don't install laravel/framework v5.6.12
    - don't install illuminate/config v5.3.23|don't install laravel/framework v5.6.12
    - don't install illuminate/config v5.3.4|don't install laravel/framework v5.6.12
    - don't install illuminate/config v5.4.0|don't install laravel/framework v5.6.12
    - don't install illuminate/config v5.4.13|don't install laravel/framework v5.6.12
    - don't install illuminate/config v5.4.17|don't install laravel/framework v5.6.12
    - don't install illuminate/config v5.4.19|don't install laravel/framework v5.6.12
    - don't install illuminate/config v5.4.27|don't install laravel/framework v5.6.12
    - don't install illuminate/config v5.4.36|don't install laravel/framework v5.6.12
    - don't install illuminate/config v5.4.9|don't install laravel/framework v5.6.12
    - don't install illuminate/config v5.5.0|don't install laravel/framework v5.6.12
    - don't install illuminate/config v5.5.16|don't install laravel/framework v5.6.12
    - don't install illuminate/config v5.5.17|don't install laravel/framework v5.6.12
    - don't install illuminate/config v5.5.2|don't install laravel/framework v5.6.12
    - don't install illuminate/config v5.5.28|don't install laravel/framework v5.6.12
    - don't install illuminate/config v5.5.33|don't install laravel/framework v5.6.12
    - don't install illuminate/config v5.5.34|don't install laravel/framework v5.6.12
    - don't install illuminate/config v5.5.35|don't install laravel/framework v5.6.12
    - don't install illuminate/config v5.5.36|don't install laravel/framework v5.6.12
    - don't install illuminate/config v5.5.37|don't install laravel/framework v5.6.12
    - don't install illuminate/config v5.5.39|don't install laravel/framework v5.6.12
    - Installation request for laravel/framework (locked at v5.6.12, required as 5.6.*) -> satisfiable by laravel/framework[v5.6.12].

Installation failed, reverting ./composer.json to its original content.

**Comment by juankstylez** [comment]
Hola ! tengo el mismo problema ! :(

**Comment by JoelCL** [comment]
@juankstylez Parece que en la versión Laravel 5.6.11 también hay ese problema, más veo por error de compatibilidad con Laravel 5.6.*... Ya que prové instalar Laravel 5.5 y este paquete "shinobi" instaló correctamente sin complicación alguna.

**Comment by JoelCL** [comment]
@juankstylez Mira, en su último **commit** registrado fue el Noviembre del año pasado, aproximadamente 4 a 5 meses atras:
<a href="https://ibb.co/gNmUzc"><img src="https://preview.ibb.co/mj7DQH/Selecci_n_005.png" alt="Selecci_n_005" border="0"></a>
Si vez, hay un **pull** registrado con un mansaje **"Add Laravel 5.6 support "**, eso significa que estan añadiendo ese soporte a Laravel 5.6, hasta indica desde cuando empezaron a hacerlo:
<a href="https://ibb.co/doy1vH"><img src="https://preview.ibb.co/c2fEFH/Selecci_n_006.png" alt="Selecci_n_006" border="0"></a>

**Comment by kaidesu** [comment]
Sorry for the delay - v3.2 has been tagged with Laravel 5.6 support
