### ISSUE TITLE
Doubt about all-access and no-access at the same time

### ISSUE THREAD

**Issue by italomoralesf** [caffeinated/shinobi#77]
To the same user I will assign two roles (one with all-access and the other with no-access).

And dominates all-access ... why?

I checked the file ShinobiTrait and I see that the first check is for no-access, but to this method the verification does not arrive

```
public function can($permissions, $arguments = [])
    {
        foreach ($this->roles as $role) {
            if ($role->special === 'no-access') {                
                return false;
            }

            if ($role->special === 'all-access') {
                return true;
            }
        }

        return $this->hasAllPermissions($permission, $this->getPermissions());
    }
```

Additional data

**Middleware**: 
```
'role' => \Caffeinated\Shinobi\Middleware\UserHasRole::class,
'permission' => \Caffeinated\Shinobi\Middleware\UserHasPermission::class,
```
**Route**:
```
Route::get('agents', 'AgentController@index')
        ->name('agents.index')
	->middleware('permission:agents.index');
```
**View**: `@can('agents.index')`

**Comment by kaidesu** [comment]
You wouldn't assign both special flags on a single role - it should always be one or the other.

It's useful for things like a Banned role type and a Super Admin role type.
