### ISSUE TITLE
@role(array)

### ISSUE THREAD

**Issue by SergioFloresG** [caffeinated/shinobi#85]
Implement the option to send several role slugs when validating in Blade.

```php
$slug = 'admin';

@role (['admin-payments', 'admin-templates', 'admin'])
...
@endrole
```

**Comment by Quacrom** [comment]
https://github.com/caffeinated/shinobi/issues/87

**Comment by kaidesu** [comment]
Any reason why you're not simply checking a permission and assigning that permission to each given role?

Roles can change over time wheres permissions act more as a source of truth for your users abilities to perform certain actions.

**Comment by kaidesu** [comment]
`@anyrole` and `@allroles` will be added as part of v4.1.0~
