### ISSUE TITLE
Can't pass $permissions as array on UserHasPermission middleware 

### ISSUE THREAD

**Issue by mazyvan** [caffeinated/shinobi#86]
`$this->middleware('permissionshinobi:manage.cotizacion,index.cotizacion')->only(['index']);`

how is supposed to send an array of permissions if the `$permissions` parameter is not set like -> `...$permissions` (using the splat operator)

![image](https://user-images.githubusercontent.com/10915753/47524245-b120a700-d85f-11e8-85c3-06d06df6adc8.png)

**Comment by cgmerida** [comment]
The same problem here.

Did you solve it?

**Comment by peric0** [comment]
Kernel.php
  'permission' => \Caffeinated\Shinobi\Middleware\UserHasPermission::class,

web.php

  Route::get('units','UnitController@index')->name('units.index')
  ->middleware('permission:units.index');

Error

Target class [Caffeinated\Shinobi\Middleware\UserHasPermission] does not exist.
