### ISSUE TITLE
@canany(['users.index', 'roles.index', 'permissions.index']) I have a module roles

### ISSUE THREAD

**Issue by christiantigre** [caffeinated/shinobi#87]
how could I use an example variation => 
@canany (['users.index', 'roles.index', 'permissions.index']) 
since I have a user module, in the main menu I would like your sample option of access to the module only if you meet any of those canany, is there any way with shinobi?

**Comment by Quacrom** [comment]
Hi, I created a small hack for the Laravel 5.5 version and it works perfect for me:

in vendor\caffeinated\shinobi\src\ShinobiServiceProvider.php add after `protected function registerBladeDirectives()`:
```
Blade::directive('canany', function ($expression) {
	return "<?php if (\\Shinobi::canany({$expression})): ?>";
});

Blade::directive('endcanany', function ($expression) {
	return '<?php endif; ?>';
});
```

in vendor\caffeinated\shinobi\src\Shinobi.php add funtion:

```
/**
 * Checks if user has the given permissions.
 *
 * @param array $permissions
 *
 * @return bool
 */
public function canany($permissions = array())
{
	if ($this->auth->check()) {
		foreach($permissions AS $permission)
		{
			$p = $this->auth->user()->can($permission);
			if($p)
			{
				return true;
			}
		}
	} else {
		$guest = Role::whereSlug('guest')->first();

		if ($guest) {
			foreach($permissions AS $permission)
			{
				$p = $guest->can($permission);
				if($p)
				{
					return true;
				}
			}
		}
	}

	return false;
}
```

After this you can use @canany en blade:

```
@canany( ['permissions_slug1', 'permissions_slug2', 'permissions_slug3'] )
code
@endcanany
```

Regards 

Jose

**Comment by kaidesu** [comment]
Not going to implement this at this time.
