### ISSUE TITLE
Models With Different Names

### ISSUE THREAD

**Issue by jfversat** [caffeinated/shinobi#89]
I have changed the models name in Models\Role.php and Models\Permission.php
for example:
 i change the table name of Role.php to G_roles and Permission.php to G_permissions,
using protected table name.
in migrations i did the same thing i prepend a "G_" to all table names, now when  i use 
ShibobiTrait in UserModel laravel throw the next error:

(4/4) ErrorException
--
SQLSTATE[42S02]: [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]El nombre de objeto **'role_user'** no es válido. (SQL: select [G_roles].*, **[role_user]**.[user_id] as [pivot_user_id], **[role_user]**.[role_id] as [pivot_role_id], [**role_user]**.[created_at] as [pivot_created_at], **[role_user]**.[updated_at] as [pivot_updated_at] from [G_roles] inner join **[role_user]** on [G_roles].[id] = **[role_user]**.[role_id] where **[role_user]**.[user_id] = 1) (View: C:\xampp\htdocs\G_project\resources\views\layouts\app.blade.php) (View: C:\xampp\htdocs\G_project\resources\views\layouts\app.blade.php)

And is confusing because it supossed to be G_role_user not role_user.
I appreciate any help you can give me.
Sorry for the english, by the way in new on github so i dont know if this is the correct place to ask.

**Comment by kaidesu** [comment]
:+1: I'll need to add config options to customize the table names for relationships - currently it's relying on Laravel to auto-guess what it should be - I don't think Laravel uses the table property in your models to determine this, but your class name directly.

**Comment by kaidesu** [comment]
sorry - what version of shinobi are you using here?

**Comment by jfversat** [comment]
> sorry - what version of shinobi are you using here?

shinobi 3.3 
laravel 5.4 
Now i'm migrating the project to laravel 5.7
