### ISSUE TITLE
Problem with Shinobi - ShinobiTrait don't exists

### ISSUE THREAD

**Issue by emaw705** [caffeinated/shinobi#95]
Hi. I can't use shinobi for Laravel 5.8 like I used shinobi for Laravel 5.6.

For example:

   + The option ShinobiTrait on module User don't work. It is beacuse the folder "src/traits" has desappeared.

   + The file UserHasPermission.php that was into folder "src/Middlewares" is not there.

How can I solve this?

Thanks.

**Comment by i6media** [comment]
Replace the ShinobiTrait with \Caffeinated\Shinobi\Concerns\HasRolesAndPermissions

**Comment by emaw705** [comment]
Thank you.

And what about the Middleware 'Permissions'? 

How can I replace it?

**Comment by kaidesu** [comment]
You can use v3.4.0 in place until I get migration docs in place :+1:
