### ISSUE TITLE
Problems adding the middleware to web.php

### ISSUE THREAD

**Issue by jarayabozo** [caffeinated/shinobi#97]
It's a part of my route/web.php file

Route::get('products', 'ProductController@index')->name('products.index')->middleware('permission:products.index');
Route::post('users/store','UserController@store')->name('users.store')->middleware('permission:users.store');

kernel.php
'role' => \Caffeinated\Shinobi\Models\Role::class,
'permission' => \Caffeinated\Shinobi\Models\Permission::class,

Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR)
Function name must be a string

Symfony\Component\Debug\Exception\FatalThrowableError 
…/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php164

Thanks

**Comment by kaidesu** [comment]
Sorry, not understanding what your problem here is.
