### ISSUE TITLE
Documentation needs an update for newest users

### ISSUE THREAD

**Issue by erickedc** [caffeinated/shinobi#99]
Hi!

I have been using Shinobi for a few years in its version 3.0.8 in Laravel 5.3 and I must say that I am impressed by how good the package is, but recently I updated my project to Laravel 5.8.* and I see that there is still no support. I have no complaints about Shinobi but it seems that the documentation is not updated in both the wiki and the website (it is down) for the new versions of the package. It would be very useful to have (at least) the updated wiki for users who did not know the package (Shinobi) and are starting to use Laravel as well.

Thanks.

**Comment by chuckrincon** [comment]
Agree with @erickedc, maybe is a good idea use GitHub pages for this purpose.  
What you think @kaidesu

**Comment by kaidesu** [comment]
Yeah, I've been trying to work on wrangling all the documentation to a single resource. All documentation will eventually be moved to https://github.com/caffeinated/website, which is the code for https://caffeinatedpackages.com/ with auto-deploy set up. So any pull requests/contributions will be instantly available upon merging!

Laravel 5.8 support is currently found within the v4.0.0-beta.3 release.

**Comment by samuelecarpene** [comment]
What about to make the 3.3 version compatible with Laravel 5.8?

A lot of things are removed in the new version 4.0.0-beta and maybe is better to deprecate methods instead of removing.
People that used your package and need to upgrade laravel from 5.7 to 5.8 must change a lot of thigs.

Thank you in advance.

**Comment by wehsoft** [comment]
> What about to make the 3.3 version compatible with Laravel 5.8?
> 
> A lot of things are removed in the new version 4.0.0-beta and maybe is better to deprecate methods instead of removing.
> People that used your package and need to upgrade laravel from 5.7 to 5.8 must change a lot of thigs.
> 
> Thank you in advance.

It is a lot of change even if it were possible to leave compatible version 3.3 with laravel 5.8 would be a great help!

**Comment by peric0** [comment]
Good afternoon I am trying to install shinobi on a clean project of laravel 5.8 and it is not possible.

  Problem 1
    - Installation request for caffeinated / shinobi ^ 3.3 -> satisfiable by caffeinated / shinobi [v3.3].
    - Conclusion: remove laravel / framework v5.8.17
    - Conclusion: do not install laravel / framework v5.8.17
    - caffeinated / shinobi v3.3 requires illuminate / config 5.3. * | 5.4. * | 5.5. * | 5.6. * | 5.7. * -> satisfiable by illuminate / config [5.3.x-dev, 5.4.x-dev, 5.5.x-dev, 5.6.x-dev, 5.7.17, 5.7.18, 5.7.19, 5.7.x-dev, v5.3.0, v5.3.16, v5.3.23, v5.3.4, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5. 5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5. 6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.39, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9, v5.7.0, v5.7.1, v5. 7.10, v5.7.11, v5.7.15, v5.7.2, v5.7.20, v5.7.21, v5.7.22, v5.7.23, v5.7.26, v5.7.27, v5.7.28, v5.7.3, v5.7.4, v5.7.5, v5.7.6, v5.7.7, v5.7.8, v5.7.9].
    - do not install illuminate / config 5.3.x-dev | do not install laravel / framework v5.8.17
    - do not install illuminate / config 5.4.x-dev | do not install laravel / framework v5.8.17
.
.
.
    - do not install illuminate / config v5.7.8 | do not install laravel / framework v5.8.17
    - do not install illuminate / config v5.7.9 | do not install laravel / framework v5.8.17
    - Installation request for laravel / framework (locked at v5.8.17, required as 5.8. *) -> satisfiable by laravel / framework [v5.8.17].

**Comment by wehsoft** [comment]
> Good afternoon I am trying to install shinobi on a clean project of laravel 5.8 and it is not possible.
> 
> Problem 1
> - Installation request for caffeinated / shinobi ^ 3.3 -> satisfiable by caffeinated / shinobi [v3.3].
> - Conclusion: remove laravel / framework v5.8.17
> - Conclusion: do not install laravel / framework v5.8.17
> - caffeinated / shinobi v3.3 requires illuminate / config 5.3. * | 5.4. * | 5.5. * | 5.6. * | 5.7. * -> satisfiable by illuminate / config [5.3.x-dev, 5.4.x-dev, 5.5.x-dev, 5.6.x-dev, 5.7.17, 5.7.18, 5.7.19, 5.7.x-dev, v5.3.0, v5.3.16, v5.3.23, v5.3.4, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5. 5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5. 6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.39, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9, v5.7.0, v5.7.1, v5. 7.10, v5.7.11, v5.7.15, v5.7.2, v5.7.20, v5.7.21, v5.7.22, v5.7.23, v5.7.26, v5.7.27, v5.7.28, v5.7.3, v5.7.4, v5.7.5, v5.7.6, v5.7.7, v5.7.8, v5.7.9].
> - do not install illuminate / config 5.3.x-dev | do not install laravel / framework v5.8.17
> - do not install illuminate / config 5.4.x-dev | do not install laravel / framework v5.8.17
> .
> .
> .
> - do not install illuminate / config v5.7.8 | do not install laravel / framework v5.8.17
> - do not install illuminate / config v5.7.9 | do not install laravel / framework v5.8.17
> - Installation request for laravel / framework (locked at v5.8.17, required as 5.8. *) -> satisfiable by laravel / framework [v5.8.17].

Okay, thank you anyway!

**Comment by kaidesu** [comment]
Tagged v3.4.0 with Laravel 5.8 support 👍Updated docs will come soon.

**Comment by kaidesu** [comment]
https://caffeinatedpackages.com/guide/packages/shinobi.html

Adding docs for both `3.4` and `4.0` :v:
